# retino

from retino.axon import *
from retino.axonsegment import *
from retino.retinoutil import *
from retino.postsynapse import *
from retino.synapse import *
from retino.plotting import *

TECTUM_SIZE_X = 100.0
TECTUM_SIZE_Y = 100.0
AXON_SEGMENT_LENGTH_AVG = 2
AXON_SEGMENT_LENGTH_STD = 0.5
AXON_SEGMENT_NOISE_STD = 0.8
AXON_SEGMENT_SYNAPSE_COUNT = 1
AXON_SEGMENT_SYNAPSE_POOL_COUNT = 4
AXON_SEGMENT_SYNAPSE_JITTER_STD = 0.4
NUMBER_OF_AXONS = 10 
NUMBER_OF_POSTSYNAPTIC_NEURONS = 50

ACTIVITY_LOSS_FACTOR = 0.25
AXON_ACTIVITY_FIRED_THRESHHOLD = 1.0

DESIRED_DIRECTION_WEIGHT = 0.6
MOMENTUM_DIRECTION_WEIGHT = 1.2

RANDOM_ORIGIN_NODE_BETA = 8
RANDOM_ORIGIN_NODE_ALPHA = 1

ASYNCHRONOUS_STIMULATION_GROWTH_RATE = 0.16
ASYNCHRONOUS_STIMULATION_LOSS_RATE = 0.14
SYNCHRONOUS_STIMULATION_GROWTH_RATE = 0.13
SYNCHRONOUS_STIMULATION_LOSS_RATE = 0.12
NO_STIMULATION_GROWTH_RATE = 0.13
NO_STIMULATION_LOSS_RATE = 0.09

